plugins:
  - jest
  - babel

env:
  jest: true
  browser: true
  es2020: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  import/extensions: 0  

parserOptions:
  ecmaVersion: 2020